# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 538)
        MainWindow.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 201, 111))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName("label")
        self.request_count = QtWidgets.QLineEdit(self.groupBox)
        self.request_count.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.request_count.setStyleSheet("border: 1px solid rgba(255,255,255,0.7);\n"
"border-radius: 5px;")
        self.request_count.setObjectName("request_count")
        self.start_simulation_btn = QtWidgets.QPushButton(self.groupBox)
        self.start_simulation_btn.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.start_simulation_btn.setStyleSheet("border: 1px solid #fff;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"text-transform: uppercase;\n"
"border-radius: 5px;")
        self.start_simulation_btn.setObjectName("start_simulation_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 360, 151, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_5.setObjectName("label_5")
        self.state_1 = QtWidgets.QLabel(self.groupBox_2)
        self.state_1.setGeometry(QtCore.QRect(90, 20, 31, 16))
        self.state_1.setStyleSheet("color: rgba(0,255,0);")
        self.state_1.setObjectName("state_1")
        self.state_2 = QtWidgets.QLabel(self.groupBox_2)
        self.state_2.setGeometry(QtCore.QRect(90, 40, 31, 16))
        self.state_2.setStyleSheet("color: rgba(0,255,0);")
        self.state_2.setObjectName("state_2")
        self.state_3 = QtWidgets.QLabel(self.groupBox_2)
        self.state_3.setGeometry(QtCore.QRect(90, 60, 31, 16))
        self.state_3.setStyleSheet("color: rgba(0,255,0);")
        self.state_3.setObjectName("state_3")
        self.state_4 = QtWidgets.QLabel(self.groupBox_2)
        self.state_4.setGeometry(QtCore.QRect(90, 80, 31, 16))
        self.state_4.setStyleSheet("color: rgba(0,255,0);")
        self.state_4.setObjectName("state_4")
        self.outer_info = QtWidgets.QTextEdit(self.centralwidget)
        self.outer_info.setGeometry(QtCore.QRect(40, 210, 371, 261))
        self.outer_info.setObjectName("outer_info")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 180, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 30, 211, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(170, 80, 21, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(170, 40, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(170, 20, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(170, 60, 31, 16))
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mass Service System"))
        self.groupBox.setTitle(_translate("MainWindow", "Simulation settings"))
        self.label.setText(_translate("MainWindow", "Requests number"))
        self.request_count.setText(_translate("MainWindow", "1000"))
        self.start_simulation_btn.setText(_translate("MainWindow", "Start"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Simalation state"))
        self.label_2.setText(_translate("MainWindow", "Channel 1 -----"))
        self.label_3.setText(_translate("MainWindow", "Channel 2 -----"))
        self.label_4.setText(_translate("MainWindow", "Channel 3 -----"))
        self.label_5.setText(_translate("MainWindow", "Channel 4 -----"))
        self.state_1.setText(_translate("MainWindow", "Free"))
        self.state_2.setText(_translate("MainWindow", "Free"))
        self.state_3.setText(_translate("MainWindow", "Free"))
        self.state_4.setText(_translate("MainWindow", "Free"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Initial Data"))
        self.label_6.setText(_translate("MainWindow", "Number of channels"))
        self.label_7.setText(_translate("MainWindow", "Intensity of input thread"))
        self.label_8.setText(_translate("MainWindow", "Intensity of service thread"))
        self.label_9.setText(_translate("MainWindow", "Algorithm type"))
        self.label_10.setText(_translate("MainWindow", "δz"))
        self.label_11.setText(_translate("MainWindow", "0.75"))
        self.label_12.setText(_translate("MainWindow", "4"))
        self.label_13.setText(_translate("MainWindow", "0.6/n"))
